<?php
namespace app\admin\controller;

class Config extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = model('Config');
    }

    public function index()
    {
        $group = input('group', 0, 'trim');
        $name  = input('name', 0, 'trim');
        $map   = ['status' => 1];
        if ($group)
        {
            $map['group'] = $group;
        }
        if ($name)
        {
            $map['name'] = ['like', '%' . $name . '%'];
        }

    }

    public function group($id = 1)
    {
        $type  = config('config_group_list');
        $where = ['status' => 1, 'group' => $id];
        $order = 'sort';
        $list  = $this->model->selectAll('', $where, $order);
        $this->assign('list', $list);
        $this->assign('id', $id);
        $this->setMeta($type[$id] . '设置');
        return $this->fetch();
    }
}