<?php
namespace app\admin\controller;

use app\admin\model;

class Index extends Admin
{
    protected $adminModel;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->adminModel = model('Admin');
    }

    public function index()
    {
        return '后台首页';
    }

    public function login($username = '', $password = '', $verify = '')
    {
        if (IS_POST)
        {
            if (!$username || !$password)
            {
                return $this->error('用户名或密码不能为空');
            }
            $captcha['captcha'] = $verify;
            $verifyRuturn       = $this->validate($captcha, [
                'captcha|验证码' => 'require|captcha'
            ]);

            if ($verifyRuturn != 'true')
            {
                return $this->error($verifyRuturn);
            }
            $result = $this->adminModel->login($username, $password);
            if ($result)
            {
                return $this->success('成功');
            } else
            {
                return $this->error('失败');
            }

        } else
        {
            return $this->fetch();
        }
    }

    public function logout()
    {
        session('admin_auth', null);
        session('admin_auth_sign', null);
    }
}

